// All the available colours
export enum noteColors {
    black = '#212121',
    white = '#ffffff',
    gray = '#eeeeee',
    yellow = '#fff9c4',
    green = '#c8e6c9',
    red = '#ffcdd2',
    orange = '#ffe0b2',
    green_blue = '#b2ebf2',
    blue = '#bbdefb',
    blue_dark = '#90caf9',
    purple = '#e1bee7',
    pink = '#f8bbd0',
    brown = '#d7ccc8',
    dark_red = '#b71c1c',
    dark_orange = '#ef6c00',
    dark_yellow = '#fbc02d',
    dark_green = '#33691e',
    dark_blue = '#01579b',
    dark_purple = '#6a1b9a',
    dark_pink = '#880e4f',
    dark_brown = '#3e2723',
    dark_gray = '#424242',
    light_red = '#ff8a80',
    light_orange = '#ffd180',
    light_yellow = '#ffff8d',
    light_green = '#a5d6a7',
    light_blue = '#80d8ff',
    light_purple = '#ea80fc',
    light_pink = '#ff80ab',
    light_brown = '#bcaaa4',
    light_gray = '#b0bec5'
}