source "https://rubygems.org"

ruby "3.2.3"

# Mongoid is an ODM (Object Document Mapper) Framework for MongoDB
gem 'mongoid'

gem 'firebase'

gem 'google-cloud-firestore'

gem 'rack-cors'

gem 'sprockets-rails'

gem 'foreman'

# Google-cloud-storage is the official library for Google Cloud Storage.
gem "google-cloud-storage"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.4", ">= 7.0.4.2"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

#factory_bot is a fixtures replacement with a straightforward definition syntax, support for multiple build strategies
gem 'factory_bot_rails'

gem 'faker'

gem 'rails-controller-testing'

gem 'uuidtools'

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem "rack-cors"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]

   # rspec-rails is a testing framework for Rails 3.x and 4.x.
  gem 'rspec-rails'
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

